# Generated by Django 4.0.5 on 2022-06-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_post_profile_email_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
