# Generated by Django 4.0.5 on 2022-06-15 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
